# sample-color-app-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default .Release.Name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "fullname" . }}-rollout
                port:
                  number: 8888
